//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturionAttachmentService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CenturionAttachmentService.IAttachmentService")]
    public interface IAttachmentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttachmentService/SecureDownload", ReplyAction="http://tempuri.org/IAttachmentService/SecureDownloadResponse")]
        System.Threading.Tasks.Task<byte[]> SecureDownloadAsync(string filepath, bool needLogin, string sharedFolder, string userCredential, string passCredential, bool needBackSide, System.Nullable<int> module, bool isExternal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttachmentService/SecureUpload", ReplyAction="http://tempuri.org/IAttachmentService/SecureUploadResponse")]
        System.Threading.Tasks.Task<string> SecureUploadAsync(byte[] sourceFile, string destinationFilePath, bool needLogin, string sharedFolder, string userCredential, string passCredential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttachmentService/TestConnection", ReplyAction="http://tempuri.org/IAttachmentService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync(bool writeOnLog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAttachmentServiceChannel : CenturionAttachmentService.IAttachmentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AttachmentServiceClient : System.ServiceModel.ClientBase<CenturionAttachmentService.IAttachmentService>, CenturionAttachmentService.IAttachmentService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AttachmentServiceClient() : 
                base(AttachmentServiceClient.GetDefaultBinding(), AttachmentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Default.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AttachmentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AttachmentServiceClient.GetBindingForEndpoint(endpointConfiguration), AttachmentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AttachmentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AttachmentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AttachmentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AttachmentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AttachmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<byte[]> SecureDownloadAsync(string filepath, bool needLogin, string sharedFolder, string userCredential, string passCredential, bool needBackSide, System.Nullable<int> module, bool isExternal)
        {
            return base.Channel.SecureDownloadAsync(filepath, needLogin, sharedFolder, userCredential, passCredential, needBackSide, module, isExternal);
        }
        
        public System.Threading.Tasks.Task<string> SecureUploadAsync(byte[] sourceFile, string destinationFilePath, bool needLogin, string sharedFolder, string userCredential, string passCredential)
        {
            return base.Channel.SecureUploadAsync(sourceFile, destinationFilePath, needLogin, sharedFolder, userCredential, passCredential);
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync(bool writeOnLog)
        {
            return base.Channel.TestConnectionAsync(writeOnLog);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Default))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Default))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7539/AttachmentService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AttachmentServiceClient.GetBindingForEndpoint(EndpointConfiguration.Default);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AttachmentServiceClient.GetEndpointAddress(EndpointConfiguration.Default);
        }
        
        public enum EndpointConfiguration
        {
            
            Default,
        }
    }
}
