"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.newVCheckModel = {
    Uid: '',
    Amount: 0,
    RegularPayment: 0,
    AddlCharges: 0,
    ServiceFee: 0,
    Notes: '',
    InvoiceNumber: '',
    InvoiceUid: '',
    RoutingNumber: '',
    RoutingConfirm: '',
    AccountNumber: '',
    AccountConfirm: '',
    CheckNumber: '',
    PayerName: '',
    PayerAddress: '',
    PayerCity: '',
    PayerState: '',
    PayerZip: '',
    Phone: '',
    Email: '',
    AddlPrincipal: 0,
    AddlUnpaidInterest: 0,
    AddlImpound: 0,
    AddlReserve: 0,
    ToLateCharges: 0,
    AcceptTerms: false,
};
exports.newPayPalModel = {
    Uid: '',
    Amount: 0,
    RegularPayment: 0,
    AddlCharges: 0,
    ServiceFee: 0,
    Notes: '',
    InvoiceNumber: '',
    InvoiceUid: '',
    Email: '',
    AcceptTerms: false,
};
exports.newCreditCardModel = {
    Uid: '',
    Amount: 0,
    RegularPayment: 0,
    AddlCharges: 0,
    ServiceFee: 0,
    Notes: '',
    InvoiceNumber: '',
    InvoiceUid: '',
    Email: '',
    Type: 0,
    Number: '',
    Cvv: '',
    OnName: '',
    LastName: '',
    BillingAddress: '',
    City: '',
    State: '',
    Zip: '',
    Description: '',
    AcceptTerms: false,
    Expiration_String: ''
};
exports.initialPendingInvoicesColumns = [
    { IsNumber: false, Checked: true, HasCustomValue: false, Position: 1, ClassName: "text-center", Align: "center", Filter: 'text', Width: 100, Title: 'Invoice', ColumnName: 'NumInvoice' },
    { IsNumber: false, Checked: true, HasCustomValue: false, Position: 2, ClassName: "text-left", Align: "left", Filter: 'text', Width: 300, Title: 'Full Name', ColumnName: 'FullName' },
    { IsNumber: false, Checked: true, HasCustomValue: false, Position: 3, ClassName: "text-center", Align: "center", Filter: 'text', Width: 100, Title: 'Account', ColumnName: 'Account' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 4, ClassName: "text-center", Align: "center", Filter: 'text', Width: 100, Title: 'Is Frozen', ColumnName: 'IsFrozenChecks' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 5, ClassName: "text-center", Align: "center", Filter: 'text', Width: 150, Title: 'Department', ColumnName: 'DepartmentUid' },
    { IsNumber: true, Checked: true, HasCustomValue: false, Position: 6, ClassName: "text-right", Align: "right", Filter: 'text', Width: 100, Title: 'Amount', ColumnName: 'Amount', Format: "{0:c}", FormatExcel: "$#,##0.00" },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 7, ClassName: "text-center", Align: "center", Filter: 'date', Width: 100, Title: 'Date', ColumnName: 'Date' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 8, ClassName: "text-center", Align: "center", Filter: 'date', Width: 100, Title: 'Date Due', ColumnName: 'DateDue' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 9, ClassName: "text-center", Align: "center", Filter: 'text', Width: 150, Title: 'Last Date Sent', ColumnName: 'SendLastEmailDate' }
];
exports.initialPaidInvoicesColumns = [
    { IsNumber: false, Checked: true, HasCustomValue: false, Position: 1, ClassName: "text-center", Align: "center", Filter: 'text', Width: 100, Title: 'Invoice', ColumnName: 'NumInvoice' },
    { IsNumber: false, Checked: true, HasCustomValue: false, Position: 2, ClassName: "text-left", Align: "left", Filter: 'text', Width: 300, Title: 'Full Name', ColumnName: 'FullName' },
    { IsNumber: false, Checked: true, HasCustomValue: false, Position: 3, ClassName: "text-center", Align: "center", Filter: 'text', Width: 100, Title: 'Account', ColumnName: 'Account' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 4, ClassName: "text-center", Align: "center", Filter: 'text', Width: 150, Title: 'Department', ColumnName: 'DepartmentUid' },
    { IsNumber: true, Checked: true, HasCustomValue: false, Position: 5, ClassName: "text-center", Align: "center", Filter: 'text', Width: 100, Title: 'Amount', ColumnName: 'Amount', Format: "{0:c}", FormatExcel: "$#,##0.00" },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 6, ClassName: "text-center", Align: "center", Filter: 'date', Width: 100, Title: 'Date', ColumnName: 'Date' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 7, ClassName: "text-center", Align: "center", Filter: 'date', Width: 100, Title: 'Date Due', ColumnName: 'DateDue' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 8, ClassName: "text-center", Align: "center", Filter: 'text', Width: 150, Title: 'Date Received', ColumnName: 'DateReceived' },
    { IsNumber: false, Checked: true, HasCustomValue: true, Position: 9, ClassName: "text-center", Align: "center", Filter: 'text', Width: 150, Title: 'Last Date Sent', ColumnName: 'SendLastEmailDate' },
];
exports.initialInvoiceDetailColumns = [
    { HasCustomValue: true, ClassName: "text-center", Width: 120, Title: 'Payment Creation', ColumnName: 'AppCreationDate' },
    { HasCustomValue: true, ClassName: "text-center", Width: 120, Title: 'Date Received', ColumnName: 'DateReceived' },
    { HasCustomValue: false, ClassName: "text-center", Width: 150, Title: 'Reference', ColumnName: 'Reference' },
    { HasCustomValue: false, ClassName: "text-center", Width: 200, Title: 'Memo', ColumnName: 'Memo' },
    { HasCustomValue: false, ClassName: "text-center", Width: 200, Title: 'Reference (Confirmation)', ColumnName: 'ReferenceLog' },
    { HasCustomValue: false, ClassName: "text-right", Width: 120, Title: 'Payment Amount', ColumnName: 'Amount', Format: "{0:c}" }
];
exports.initialInvoiceDetailsColumns = [
    { IsNumber: false, HasCustomValue: true, Align: "center", Width: 100, Title: 'Begin Date', ColumnName: 'BeginDate' },
    { IsNumber: false, HasCustomValue: true, Align: "center", Width: 100, Title: 'End Date', ColumnName: 'EndDate' },
    { IsNumber: false, HasCustomValue: false, Align: "left", Width: 250, Title: 'Name', ColumnName: 'Name' },
    { IsNumber: false, HasCustomValue: false, Align: "center", Width: 100, Title: 'Account', ColumnName: 'Account' },
    { IsNumber: false, HasCustomValue: false, Align: "center", Width: 100, Title: 'Loan Account', ColumnName: 'LoanAcct' },
    { IsNumber: false, HasCustomValue: false, Align: "left", Width: 350, Title: 'Borrower', ColumnName: 'Borrower' },
    { IsNumber: false, HasCustomValue: false, Align: "left", Width: 300, Title: 'Prop Street', ColumnName: 'PropStreet' },
    { IsNumber: false, HasCustomValue: false, Align: "center", Width: 100, Title: 'Prop City', ColumnName: 'PropCity' },
    { IsNumber: false, HasCustomValue: false, Align: "center", Width: 150, Title: 'Prop State', ColumnName: 'PropState' },
    { IsNumber: false, HasCustomValue: false, Align: "center", Width: 100, Title: 'Prop Zip', ColumnName: 'PropZip' },
    { IsNumber: false, HasCustomValue: false, Align: "center", Width: 150, Title: 'Loan Status', ColumnName: 'LoanStatus' },
    { IsNumber: false, HasCustomValue: false, Align: "left", Width: 300, Title: 'Description', ColumnName: 'Description' },
    { IsNumber: true, HasCustomValue: false, Align: "center", Width: 80, Title: 'Quantity', ColumnName: 'Quantity' },
    { IsNumber: true, HasCustomValue: false, Align: "right", Width: 100, Title: 'Amount', ColumnName: 'Amount', Format: "{0:c}", FormatExcel: "$#,##0.00" },
];
//# sourceMappingURL=InvoicesCommon.js.map