//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCheckService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VCheckModel", Namespace="http://schemas.datacontract.org/2004/07/FCI.Services.Wcf")]
    public partial class VCheckModel : object
    {
        
        private string account_numberField;
        
        private decimal amountField;
        
        private string check_numberField;
        
        private string confirmation_numberField;
        
        private string emailField;
        
        private decimal fci_addl_chargesField;
        
        private decimal fci_addl_impoundField;
        
        private decimal fci_addl_principalField;
        
        private decimal fci_addl_reserveField;
        
        private decimal fci_addl_unpaid_interestField;
        
        private int fci_dbidField;
        
        private string fci_guidField;
        
        private string fci_loanrecidField;
        
        private string fci_notesField;
        
        private string fci_phoneField;
        
        private int fci_pmt_countField;
        
        private VCheckService.VChkPmtSource fci_pmtsourceField;
        
        private decimal fci_regular_paymentField;
        
        private decimal fci_service_feeField;
        
        private decimal fci_to_latechargesField;
        
        private string fci_useridField;
        
        private string fci_usernameField;
        
        private bool fci_waivelatechargeField;
        
        private string invoice_numberField;
        
        private string invoice_uidField;
        
        private string memo1Field;
        
        private string memo2Field;
        
        private string payer_addressField;
        
        private string payer_cityField;
        
        private string payer_nameField;
        
        private string payer_phone_areaField;
        
        private string payer_phone_prefixField;
        
        private string payer_phone_suffixField;
        
        private string payer_stateField;
        
        private string payer_zipField;
        
        private string routing_numberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string account_number
        {
            get
            {
                return this.account_numberField;
            }
            set
            {
                this.account_numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string check_number
        {
            get
            {
                return this.check_numberField;
            }
            set
            {
                this.check_numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string confirmation_number
        {
            get
            {
                return this.confirmation_numberField;
            }
            set
            {
                this.confirmation_numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_addl_charges
        {
            get
            {
                return this.fci_addl_chargesField;
            }
            set
            {
                this.fci_addl_chargesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_addl_impound
        {
            get
            {
                return this.fci_addl_impoundField;
            }
            set
            {
                this.fci_addl_impoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_addl_principal
        {
            get
            {
                return this.fci_addl_principalField;
            }
            set
            {
                this.fci_addl_principalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_addl_reserve
        {
            get
            {
                return this.fci_addl_reserveField;
            }
            set
            {
                this.fci_addl_reserveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_addl_unpaid_interest
        {
            get
            {
                return this.fci_addl_unpaid_interestField;
            }
            set
            {
                this.fci_addl_unpaid_interestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fci_dbid
        {
            get
            {
                return this.fci_dbidField;
            }
            set
            {
                this.fci_dbidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fci_guid
        {
            get
            {
                return this.fci_guidField;
            }
            set
            {
                this.fci_guidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fci_loanrecid
        {
            get
            {
                return this.fci_loanrecidField;
            }
            set
            {
                this.fci_loanrecidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fci_notes
        {
            get
            {
                return this.fci_notesField;
            }
            set
            {
                this.fci_notesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fci_phone
        {
            get
            {
                return this.fci_phoneField;
            }
            set
            {
                this.fci_phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fci_pmt_count
        {
            get
            {
                return this.fci_pmt_countField;
            }
            set
            {
                this.fci_pmt_countField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VCheckService.VChkPmtSource fci_pmtsource
        {
            get
            {
                return this.fci_pmtsourceField;
            }
            set
            {
                this.fci_pmtsourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_regular_payment
        {
            get
            {
                return this.fci_regular_paymentField;
            }
            set
            {
                this.fci_regular_paymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_service_fee
        {
            get
            {
                return this.fci_service_feeField;
            }
            set
            {
                this.fci_service_feeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fci_to_latecharges
        {
            get
            {
                return this.fci_to_latechargesField;
            }
            set
            {
                this.fci_to_latechargesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fci_userid
        {
            get
            {
                return this.fci_useridField;
            }
            set
            {
                this.fci_useridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fci_username
        {
            get
            {
                return this.fci_usernameField;
            }
            set
            {
                this.fci_usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool fci_waivelatecharge
        {
            get
            {
                return this.fci_waivelatechargeField;
            }
            set
            {
                this.fci_waivelatechargeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice_number
        {
            get
            {
                return this.invoice_numberField;
            }
            set
            {
                this.invoice_numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice_uid
        {
            get
            {
                return this.invoice_uidField;
            }
            set
            {
                this.invoice_uidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo1
        {
            get
            {
                return this.memo1Field;
            }
            set
            {
                this.memo1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo2
        {
            get
            {
                return this.memo2Field;
            }
            set
            {
                this.memo2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_address
        {
            get
            {
                return this.payer_addressField;
            }
            set
            {
                this.payer_addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_city
        {
            get
            {
                return this.payer_cityField;
            }
            set
            {
                this.payer_cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_name
        {
            get
            {
                return this.payer_nameField;
            }
            set
            {
                this.payer_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_phone_area
        {
            get
            {
                return this.payer_phone_areaField;
            }
            set
            {
                this.payer_phone_areaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_phone_prefix
        {
            get
            {
                return this.payer_phone_prefixField;
            }
            set
            {
                this.payer_phone_prefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_phone_suffix
        {
            get
            {
                return this.payer_phone_suffixField;
            }
            set
            {
                this.payer_phone_suffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_state
        {
            get
            {
                return this.payer_stateField;
            }
            set
            {
                this.payer_stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payer_zip
        {
            get
            {
                return this.payer_zipField;
            }
            set
            {
                this.payer_zipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string routing_number
        {
            get
            {
                return this.routing_numberField;
            }
            set
            {
                this.routing_numberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VChkPmtSource", Namespace="http://schemas.datacontract.org/2004/07/FCI.Services.Wcf")]
    public enum VChkPmtSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BorrowerPortal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIRS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LenderUser = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceAdmin = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VCheckService.IVCheckService")]
    public interface IVCheckService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVCheckService/GetVCheckModel", ReplyAction="http://tempuri.org/IVCheckService/GetVCheckModelResponse")]
        System.Threading.Tasks.Task<VCheckService.VCheckModel> GetVCheckModelAsync(int dbid, string loanrecid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVCheckService/ToVCheckAction", ReplyAction="http://tempuri.org/IVCheckService/ToVCheckActionResponse")]
        System.Threading.Tasks.Task<bool> ToVCheckActionAsync(VCheckService.VCheckModel vchk);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVCheckService/FromVCheckAction")]
        System.Threading.Tasks.Task FromVCheckActionAsync(VCheckService.VCheckModel vchk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVCheckService/GetVCheckInvoiceModel", ReplyAction="http://tempuri.org/IVCheckService/GetVCheckInvoiceModelResponse")]
        System.Threading.Tasks.Task<VCheckService.VCheckModel> GetVCheckInvoiceModelAsync(string CustomerUid, string InvoiceUid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IVCheckServiceChannel : VCheckService.IVCheckService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class VCheckServiceClient : System.ServiceModel.ClientBase<VCheckService.IVCheckService>, VCheckService.IVCheckService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VCheckServiceClient() : 
                base(VCheckServiceClient.GetDefaultBinding(), VCheckServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVCheckService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VCheckServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VCheckServiceClient.GetBindingForEndpoint(endpointConfiguration), VCheckServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VCheckServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VCheckServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VCheckServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VCheckServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VCheckServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VCheckService.VCheckModel> GetVCheckModelAsync(int dbid, string loanrecid)
        {
            return base.Channel.GetVCheckModelAsync(dbid, loanrecid);
        }
        
        public System.Threading.Tasks.Task<bool> ToVCheckActionAsync(VCheckService.VCheckModel vchk)
        {
            return base.Channel.ToVCheckActionAsync(vchk);
        }
        
        public System.Threading.Tasks.Task FromVCheckActionAsync(VCheckService.VCheckModel vchk)
        {
            return base.Channel.FromVCheckActionAsync(vchk);
        }
        
        public System.Threading.Tasks.Task<VCheckService.VCheckModel> GetVCheckInvoiceModelAsync(string CustomerUid, string InvoiceUid)
        {
            return base.Channel.GetVCheckInvoiceModelAsync(CustomerUid, InvoiceUid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVCheckService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVCheckService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:3245/VCheckService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VCheckServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVCheckService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VCheckServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVCheckService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVCheckService,
        }
    }
}
